"""Bat-file generator for BBOX fiscal printer operations."""

from __future__ import annotations

import json
import os
from typing import List, Optional

from .models import Receipt, StornoReceipt
from .printer import (
    ENDPOINT_PRINT,
    ENDPOINT_REPRINT,
    build_receipt_payload,
    build_storno_payload,
    printer_base_url,
)

# ---------------------------------------------------------------------------
# Templates
# ---------------------------------------------------------------------------

_BAT_HEADER = """\
@echo off
REM Generated by bboxfixer
REM {description}
"""

_CURL_REPRINT = """\
curl -s -X POST "{base_url}{endpoint}?FN={fiscal_number}" ^
  -o NUL
if %errorlevel% neq 0 (
    echo ERROR: reprint failed for receipt {fiscal_number}
    exit /b %errorlevel%
)
echo Reprint sent for receipt {fiscal_number}
"""

_CURL_PRINT = """\
curl -s -X POST "{base_url}{endpoint}" ^
  -H "Content-Type: application/json" ^
  -d "{payload}" ^
  -o NUL
if %errorlevel% neq 0 (
    echo ERROR: print command failed
    exit /b %errorlevel%
)
echo Print command sent
"""

_BAT_FOOTER = """\
echo Done.
"""


def _escape_for_bat(json_str: str) -> str:
    """Escape a JSON string so it is safe inside Windows bat double-quotes.

    Specifically:
    * Double-quotes become ``\\"`` so the shell sees ``"``
    * Percent signs are doubled (``%%``) to avoid variable expansion
    """
    json_str = json_str.replace('"', '\\"')
    json_str = json_str.replace("%", "%%")
    return json_str


# ---------------------------------------------------------------------------
# Generator class
# ---------------------------------------------------------------------------


class BatFileGenerator:
    """Generate ``.bat`` files that reprint or storno BBOX fiscal receipts.

    Parameters
    ----------
    host:
        IP address or hostname of the BBOX fiscal printer (or its middleware).
    port:
        HTTP port of the BBOX middleware (default: 5618).
    output_dir:
        Directory where the generated ``.bat`` files will be written.
    """

    def __init__(
        self,
        host: str = "localhost",
        port: int = 5618,
        output_dir: str = "output",
    ) -> None:
        self.host = host
        self.port = port
        self.output_dir = output_dir
        self._base_url = printer_base_url(host, port)

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def generate_reprint_bat(self, receipt: Receipt) -> str:
        """Generate a ``.bat`` file that reprints *receipt* and return its path."""
        filename = f"reprint_{receipt.receipt_number}.bat"
        content = self._reprint_bat_content(receipt)
        return self._write_bat(filename, content)

    def generate_storno_bat(self, receipt: Receipt, reason: str = "Cancellation") -> str:
        """Generate a ``.bat`` file for a storno document and return its path."""
        storno = StornoReceipt(
            original_receipt_number=receipt.receipt_number,
            date=receipt.date,
            cashier=receipt.cashier,
            reason=reason,
            items=receipt.items,
        )
        filename = f"storno_{receipt.receipt_number}.bat"
        content = self._storno_bat_content(storno)
        return self._write_bat(filename, content)

    def generate_all(
        self,
        receipts: List[Receipt],
        mode: str = "both",
        storno_reason: str = "Cancellation",
    ) -> List[str]:
        """Generate bat files for a list of receipts.

        Parameters
        ----------
        receipts:
            Receipts to process.
        mode:
            One of ``"reprint"``, ``"storno"``, or ``"both"``.
        storno_reason:
            Reason text added to every storno document.

        Returns
        -------
        List of file paths that were written.
        """
        if mode not in {"reprint", "storno", "both"}:
            raise ValueError(f"Invalid mode {mode!r}; choose reprint, storno, or both")

        os.makedirs(self.output_dir, exist_ok=True)
        paths: List[str] = []

        for receipt in receipts:
            if mode in ("reprint", "both"):
                paths.append(self.generate_reprint_bat(receipt))
            if mode in ("storno", "both"):
                paths.append(self.generate_storno_bat(receipt, reason=storno_reason))

        return paths

    # ------------------------------------------------------------------
    # Private helpers
    # ------------------------------------------------------------------

    def _reprint_bat_content(self, receipt: Receipt) -> str:
        header = _BAT_HEADER.format(
            description=f"Reprint receipt {receipt.receipt_number}"
        )
        body = _CURL_REPRINT.format(
            base_url=self._base_url,
            endpoint=ENDPOINT_REPRINT,
            fiscal_number=receipt.receipt_number,
        )
        return header + body + _BAT_FOOTER

    def _storno_bat_content(self, storno_receipt: StornoReceipt) -> str:
        payload = build_storno_payload(storno_receipt)
        payload_str = json.dumps(payload, ensure_ascii=False, separators=(",", ":"))
        escaped = _escape_for_bat(payload_str)

        header = _BAT_HEADER.format(
            description=f"Storno for receipt {storno_receipt.original_receipt_number}"
        )
        body = _CURL_PRINT.format(
            base_url=self._base_url,
            endpoint=ENDPOINT_PRINT,
            payload=escaped,
        )
        return header + body + _BAT_FOOTER

    def _write_bat(self, filename: str, content: str) -> str:
        os.makedirs(self.output_dir, exist_ok=True)
        path = os.path.join(self.output_dir, filename)
        with open(path, "w", encoding="utf-8", newline="\r\n") as fh:
            fh.write(content)
        return path
